version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: react-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    environment:
      - REACT_APP_API=http://<YOUR-ALB-DNS>
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

