services:

  backend:
    build:
      context: ./backend
    container_name: employee-backend

    env_file:
      - ./backend/.env

    expose:
      - "5000"

    restart: unless-stopped


  frontend:
    build:
      context: ./frontend

    container_name: employee-frontend

    ports:
      - "80:80"

    depends_on:
      - backend

    restart: unless-stopped