apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: cloudethix-1
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: ***********
  MYSQL_DATABASE: employee_db
  MYSQL_USER: employee_user
  MYSQL_PASSWORD: **********
