apiVersion: v1
kind: Pod
metadata:
  name: sa-test
spec:
  serviceAccountName: app-sa
  containers:
    - name: toolbox
      image: docker.io/payalkharat/kubernetes-toolbox:latest
      imagePullPolicy: IfNotPresent 
      