apiVersion: v1
kind: Pod
metadata:
  name: secret-inspector
spec:
  containers:
    - name: toolbox
      image: docker.io/payalkharat/kubernetes-toolbox:latest
      imagePullPolicy: IfNotPresent
      env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/app/secrets
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: db-credentials
