apiVersion: v1
kind: Pod
metadata:
  name: config-inspector
spec:
  containers:
    - name: toolbox
      image: docker.io/payalkharat/kubernetes-toolbox:latest
      env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_ENV
      volumeMounts:
        - name: app-config-volume
          mountPath: /etc/app/config
  volumes:
    - name: app-config-volume
      configMap:
        name: app-config