apiVersion: v1
kind: Pod
metadata:
  name: config-subpath
spec:
  containers:
    - name: toolbox
      image: docker.io/payalkharat/kubernetes-toolbox:latest
      volumeMounts:
        - name: app-config-volume
          mountPath: /etc/app/name.txt
          subPath: APP_NAME
  volumes:
    - name: app-config-volume
      configMap:
        name: app-config