apiVersion: v1
kind: Pod
metadata:
  name: order-service
spec:
  containers:
    - name: order-service
      image: docker.io/payalkharat/kubernetes-toolbox:v2
      imagePullPolicy: IfNotPresent