apiVersion: v1
kind: Pod
metadata:
  name: pod-b
spec:
  containers:
    - name: toolbox
      image: docker.io/payalkharat/kubernetes-toolbox:latest
      volumeMounts:
        - name: shared-storage
          mountPath: /data
  volumes:
    - name: shared-storage
      persistentVolumeClaim:
        claimName: shared-pvc